---
## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
remote: origin
target-branch: main
chart-dirs:
  - helm
chart-repos:
  - oodle-ai=https://oodle-ai.github.io/helm-charts
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
exclude-deprecated: true
excluded-charts: []
release-label: app.kubernetes.io/instance
