apiVersion: v2
appVersion: 1.0.0
description: Helm chart for deploying the Oodle Agent that connects to Oodle Gateway
  for reverse proxy capabilities.
name: oodle-agent
type: application
version: 0.1.0
